title: Projeto de Extensão - Modelagem Drone Quadricóptero 
description: Projeto de Extensão UFPA - (Universidade Federal do Pará) FEE - (Faculdade de Engenharia Elétrica) Campus Universitário de Tucuruí.

theme: null

# debug:
#   compress: true
#   dist: false
#   shortcodes: true

readme_index:
  with_frontmatter: true

plugins:
  - jemoji
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - Makefile
  - CNAME
  - LICENSE
  - update.sh
  - Gemfile
  - Gemfile.lock
  - requirements.txt
  - node_modules
  - package.json
  - package-lock.json
  - webpack.config.js
  - jekyll-rtd-theme.gemspec
